name: CI/CD - Secure CRUD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/inventory-crud:latest .

      - name: Tag image with commit SHA
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/inventory-crud:latest \
          ${{ secrets.DOCKERHUB_USERNAME }}/inventory-crud:${{ github.sha }}

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-crud:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/inventory-crud:${{ github.sha }}
